loom.platform = neoforge
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configureondemand=true
# Mod properties
mod.version=5.9.0
mod.group=com.rbasamoyai
mod.id=createbigcannons

loom.ignoreDependencyLoomVersionValidation=true
# Mod setup
deps.fabric_loader_version=0.16.5
deps.forge_loader_version=47.3.0
deps.neoforge_loader_version=[VERSIONED]
deps.neoforge_patch_version=[VERSIONED]
deps.parchment_version=[VERSIONED]
deps.mixin_extras_version=0.4.1

# Mod Deps
# Fabric
deps.fabric_api_version=0.91.0
# Create - Fabric
deps.create_fabric_version=[VERSIONED]
# Create - Forge
deps.create_forge_version=6.0.4
deps.ponder_forge_version=1.0.52
deps.registrate_forge_version=[VERSIONED]
deps.flywheel_forge_version=1.0.2
# Other libraries
deps.rpl_version=2.1.0-dev
deps.rpl_build=190
# To use this, put the Ritchie's Projectile Library jars in the libs/ folder of each subproject.
# IMPORTANT: Keep this FALSE on remote, do not commit this file with this value set to true.
deps.use_local_rpl_build=false
deps.unify_forge_version=[VERSIONED]
# TODO unify fabric version
deps.fabric_recipe_viewer=emi
# JEI
deps.jei_version=[VERSIONED]
# Other recipe viewers
deps.rei_version=[VERSIONED]
deps.emi_version=[VERSIONED]
# Dev QoL
deps.spark_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.lazydfu_version=[VERSIONED]
# Compatibility
deps.copycats_version=3.0.0
deps.framedblocks_version=9.4.1
deps.curios_version=5.9.1
deps.trinkets_version=3.7.0
deps.cca_version=5.2.1
# Compatibility version requirements
deps.copycats_breaks_fabric=[VERSIONED]
deps.trinkets_breaks_fabric=[VERSIONED]
