org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
#org.gradle.configureondemand=true

# Minecraft and Java properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
enabled_platforms=neoforge
java_version=21

# Mod properties
mod_version=5.11.7
mod_name=Create Big Cannons
mod_id=createbigcannons
mod_author=rbasamoyai
mod_group=com.rbasamoyai
credits=
mod_license=MIT and CC BY-NC-SA (see github for details)
description=Artillery engineering comes to Create
mod_sources=https://github.com/Cannoneers-of-Create/CreateBigCannons
mod_issues=https://github.com/Cannoneers-of-Create/CreateBigCannons/issues

# Mod setup
parchment_version=2024.11.17

# Mod Deps
parchment_minecraft=1.21.1

# NeoForge
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)

# Create - NeoForge
create_neoforge_version=6.0.10-280
create_version_range=[6.0.7,6.1.0)
ponder_neoforge_version=1.0.82
registrate_neoforge_version=MC1.21-1.3.0+67
flywheel_neoforge_version=1.0.6

# Other libraries
rpl_version=2.1.2
rpl_build=199
# To use this, put the Ritchie's Projectile Library jars in the libs/ folder of each subproject.
# IMPORTANT: Keep this FALSE on remote, do not commit this file with this value set to true.
use_rpl_nightly=false
rpl_neoforge_version_range=2.1.2

# JEI
jei_version=19.27.0.340
# Other recipe viewers
rei_version=12.0.626
emi_version=1.0.9
# Dev QoL
spark_version=1.10.124

# Compatibility
copycats_version=3.0.4
copycats_version_range=3.0.0

framedblocks_version=10.5.3
framedblocks_version_range=10.0.0

curios_version=9.5.1
curios_version_range=9.2.0

sable_version=2.0.1
sable_version_range=2.0.0

# Used for Simulated, Aeronautics, and Offroad
simulated_version=1.3.0
simulated_version_range=1.3.0
