org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configureondemand=true

# Minecraft and Java properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
enabled_platforms=neoforge
java_version=21

# Mod properties
mod_version=5.10.2
mod_name=Create Big Cannons
mod_id=createbigcannons
mod_author=rbasamoyai
mod_group=com.rbasamoyai
credits=
mod_license=MIT and CC BY-NC-SA (see github for details)
description=Artillery engineering comes to Create
mod_sources=https://github.com/Cannoneers-of-Create/CreateBigCannons
mod_issues=https://github.com/Cannoneers-of-Create/CreateBigCannons/issues

# Mod setup
fabric_loader_version=0.16.14
parchment_version=2024.11.17
mixin_extras_version=0.3.5

# Mod Deps
parchment_minecraft=1.21.1

# NeoForge
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.206
neoforge_loader_version_range=[4,)

# Fabric
fabric_api_version=0.116.4

# Create - Fabric
# create_fabric_version=6.0.8.1+mc1.20.1-build.1653

# Create - NeoForge
create_neoforge_version=6.0.8-168
ponder_neoforge_version=1.0.64
registrate_neoforge_version=MC1.21-1.3.0+62
flywheel_neoforge_version=1.0.5

# Other libraries
rpl_version=2.1.1
rpl_build=195
# To use this, put the Ritchie's Projectile Library jars in the libs/ folder of each subproject.
# IMPORTANT: Keep this FALSE on remote, do not commit this file with this value set to true.
use_rpl_nightly=false
#deps.unify_forge_version=[VERSIONED]
# TODO unify fabric version
fabric_recipe_viewer=emi
# JEI
jei_version=19.27.0.340
# Other recipe viewers
rei_version=12.0.626
emi_version=1.0.9
# Dev QoL
spark_version=1.10.124
modmenu_version=7.2.1
lazydfu_version=0.1.3

# Compatibility
copycats_version=3.0.2
copycats_version_range=3.0.0
copycats_breaks_fabric=<1.20.1-1.2.5

framedblocks_version=10.3.2
framedblocks_version_range=10.3.0

curios_version=9.5.1
curios_version_range=9.5.0

trinkets_version=3.7.0
cca_version=5.2.1
trinkets_breaking=<3.7.0
