package rbasamoyai.createbigcannons.config;

import net.createmod.catnip.config.ConfigBase;

public class CBCCfgCompat extends ConfigBase {

    public final ConfigGroup sableCompat = group(0, "sable", "Sable");
    public final ConfigFloat sableRecoilMultiplier = f(40, 0, "sableRecoilMultiplier", Comments.sableRecoilMultiplier);
    public final ConfigFloat sableImpactForceMultiplier = f(40, 0, "sableImpactForceMultiplier", Comments.sableImpactForceMultiplier);
    public final ConfigBool sableProjectilesInheritPhysicsObjectVelocity = b(true, "sableProjectilesInheritPhysicsObjectVelocity");
    public final ConfigBool sableFuzedProjectilesCanExplodeAsPhysicsObject = b(true, "sableFuzedProjectilesCanExplodeAsPhysicsObject", Comments.sableFuzedProjectilesCanExplodeAsPhysicsObject);

    @Override public String getName() { return "compat"; }

    private static class Comments {
        static String sableRecoilMultiplier = "How much the recoil force generated by cannons is multiplied by when firing from a Sable physics object.";
        static String sableImpactForceMultiplier = "How much the impact force generated by projectiles is multiplied by when hitting a Sable physics object.";
        static String sableFuzedProjectilesCanExplodeAsPhysicsObject = "Whether shell blocks on physics objects fuzed with impact and inertia fuzes can detonate.";
    }

}
