modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/Cannoneers-of-Create/CreateBigCannons/issues"
license = "MIT and CC BY-NC-SA (see github for details)"

[[mods]]
modId = "createbigcannons"
version = "${version}"
displayName = "Create Big Cannons"
authors = "rbasamoyai"
description = """Artillery engineering comes to Create
Attributions:
Logo by Milkyfur
Textures by rbasamoyai, Milkyfur, and LopyLuna
"""
logoFile = "icon.png"

[[mixins]]
config = "createbigcannons-common.mixins.json"

[[mixins]]
config = "createbigcannons.mixins.json"

[[dependencies.createbigcannons]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId = "create"
type = "required"
versionRange="[${create_version},)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.createbigcannons]]
#modId = "unify"
#type = "optional"
# replace version range
#ordering = "NONE"
#side = "BOTH"

[[dependencies.createbigcannons]]
modId = "copycats"
type = "optional"
versionRange = "[${copycats_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId = "framedblocks"
type = "optional"
versionRange = "[${framedblocks_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createbigcannons]]
modId = "curios"
type = "optional"
versionRange = "[${curios_version_range},)"
ordering = "NONE"
side = "BOTH"
