plugins {
    id "multiloader-loader"
    id "net.neoforged.moddev"
	id "maven-publish"
}

var ci = System.getenv("CI")?.toBoolean() ?: false
var release = System.getenv("RELEASE")?.toBoolean() ?: false
var nightly = ci && !release
var buildNumber = System.getenv("GITHUB_RUN_NUMBER")?.toIntOrNull()
version = "${mod_version}${if (release) "" else "-dev"}+mc.${minecraft_version}-neoforge${if (nightly) "-build.${buildNumber}" else ""}"
group = "${group}.neoforge"
base.archivesName = mod_id

//val commonBundle: Configuration by configurations.creating {
//	isCanBeConsumed = false
//	isCanBeResolved = true
//}
//
//val shadowBundle: Configuration by configurations.creating {
//	isCanBeConsumed = false
//	isCanBeResolved = true
//}

//configurations {
//	compileClasspath.get().extendsFrom(commonBundle)
//	runtimeClasspath.get().extendsFrom(commonBundle)
//	get("developmentNeoForge").extendsFrom(commonBundle)
//}

neoForge {
    // Automatically enable NeoForge AccessTransformers if the file exists
    def at = project(":common").file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        //accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraft_version = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }

//        create("datagen_fabric") {
//            data()
//
//            programArgs("--mod", mod.id)
//            programArgs("--output", "${project.rootProject.file("fabric/src/generated/resources")}")
//            programArgs("--existing", "${project.rootProject.file("src/main/resources")}")
//            programArg("--all")
//            vmArg("-Dcreatebigcannons.datagen.platform=fabric")
//        }
        data {
            data()

            programArguments.addAll(
                "--mod", mod_id,
                "--output", "${project.rootProject.file("neoforge/src/generated/resources")}",
                "--existing", "${project.rootProject.file("src/main/resources")}",
                "--all")
            //vmArg "-Dcreatebigcannons.datagen.platform=neoforge" TODO figure this out
        }
//        all {
//            isIdeConfigGenerated = true
//            runDir = "../../../run"
//            vmArgs("-Dmixin.debug.export=true")
//        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven { url = "https://maven.createmod.net" } // Create, Flywheel, Ponder
    maven { url = "https://maven.neoforged.net/releases/" }
	maven { url = "https://maven.theillusivec4.top/" } // Curios
	maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
}

dependencies {
	// Create and its dependencies
	implementation("com.simibubi.create:create-${minecraft_version}:${create_neoforge_version}:slim") { transitive = false }
	implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${"ponder_neoforge_version"}")
	compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_neoforge_version}")
	runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_neoforge_version}")
	implementation("com.tterrag.registrate:Registrate:${registrate_neoforge_version}")

	// Development QOL
	runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}") { transitive = false }

	// if you would like to add integration with JEI, uncomment this line.
	compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")

	//implementation("curse.maven:spark-361579:${spark_forge_file}") // Spark

	// Ritchie's Projectile Library
    String rplSuffix = Boolean.valueOf(use_rpl_nightly) ? "-build.${rpl_build}" : ""
	implementation("com.rbasamoyai:ritchiesprojectilelib:${rpl_version}+mc.${minecraft_version}-neoforge$rplSuffix") { transitive = false }
	// Create: Unify
	// implementation("maven.modrinth:create-unify:${mod.dep("unify_forge_file")}") fixme

	// Fixes, integration
	//implementation("com.copycatsplus:copycats:${copycats_version}+mc.${minecraft_version}-neoforge") { transitive = false }
    implementation("maven.modrinth:framedblocks:${framedblocks_version}")

	// Curios
	runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}")
	compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+${minecraft_version}:api")

//    commonBundle(project(project(":common").path, "namedElements")) { transitive = false }
//    shadowBundle(project(project(":common").path, "transformProductionNeoForge")) { transitive = false }
    // TODO ok what do these do
}

//publishing {
//	publications {
//		register("mavenJava", MavenPublication) {
//			artifact(tasks.remapJar)
//			artifact(tasks.remapSourcesJar)
//			group = mod_group
//			artifactId = mod_id
//		}
//	}
//}

tasks.jar {
	archiveClassifier = "dev"
}

tasks.remapJar {
	injectAccessWidener = true
	input = tasks.shadowJar.get().archiveFile
	archiveClassifier = null
	dependsOn(tasks.shadowJar)
}

tasks.shadowJar {
	configurations = listOf(shadowBundle)
	archiveClassifier = "dev-shadow"
	exclude("fabric.mod.json")
}

sourceSets.main {
	resources { // include generated resources in resources
		srcDir("src/generated/resources")
		exclude("src/generated/resources/.cache")
	}
}

tasks.register<Copy>("buildAndCollect") {
	group = "build"
	from(tasks.remapJar.get().archiveFile, tasks.remapSourcesJar.get().archiveFile)
	into(rootProject.layout.buildDirectory.file("libs/${mod.version}/$loader"))
	dependsOn("build")
}
